import data from './placeholder-images.json';

export type ImagePlaceholder = {
  id: string;
  description: string;
  imageUrl: string;
  imageHint: string;
};

// This file is now deprecated and will be removed in a future step.
// Images are now generated by AI or will be stored in Firebase Storage.
export const PlaceHolderImages: ImagePlaceholder[] = data.placeholderImages;
